# Project
version=5.4.0
java_version=21

# Metadata
mod_name=TravelersTitles
mod_full_name=Traveler's Titles
mod_id=travelerstitles
mod_author=YUNGNICKYOUNG
mod_description=Epic, RPG-like titles when entering biomes & dimensions
mod_credits=Thanks so much to all my patrons!
license=LGPLv3
maven_group=com.yungnickyoung.minecraft.travelerstitles
mc_version=1.21.10
mc_version_range=[1.21.5, 1.22)
mc_version_range_fabric=>=1.21.5
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# CurseForge/Modrinth Publishing
curseforgegradle_version=1.1.15
compatible_versions=1.21.5
curseforge_project_id_fabric=590990
curseforge_project_id_neoforge=504908
modrinth_project_id=JtifUr64
debug_publish=true

# Fabric
fabric_version=0.138.3
fabric_loader_version=0.18.1
clothconfig_version_fabric=18.0.145
modmenu_version_fabric=16.0.0-rc.1

# NeoForge
neoforge_version=21.10.32-beta
neoforge_version_range=[21.10.32-beta,)
neoforge_loader_version_range=[4,)
waystones_fileid_neoforge=6370610
balm_fileid_neoforge=6371923

# Credentials for publishing. Gets overwritten with global gradle.properties.
curseforgeApiKey=""
modrinthToken=""

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true